### ISSUE TITLE
can't create project with title > 50 chars

### ISSUE THREAD

**Issue by funkyminh** [kanboard/python-api-client#2]
hello,
it seems that project_id return false when name is over 50 chars ? In database, projects name is a varchar with a max lenght of 255 chars.
```
from kanboard import Kanboard

kb = Kanboard("http://localhost/jsonrpc.php", "jsonrpc", "your_api_token")
project_id = kb.create_project(name="My project over 50 chars")
```

**Comment by fguillot** [comment]
There is a validation rule to limit the title to 50 chars: 
https://github.com/kanboard/kanboard/blob/master/app/Validator/ProjectValidator.php#L31

This value could be bumped to 255
