### ISSUE TITLE
Install via pip fails on Debian jessie/Python 3.4

### ISSUE THREAD

**Issue by adnidor** [kanboard/python-api-client#5]
pip.log: https://gist.github.com/adnidor/872a3fc3c51b082d1564b594eed8aa53

Error: `ImportError: <module 'setuptools.dist' from '/usr/lib/python3/dist-packages/setuptools/dist.py'> has no 'check_specifier' attribute`

Command: `pip3 install kanboard` as root

**Comment by dalito** [comment]
Most likely your setuptools version is to old. Try to update

`pip2 install -U setuptools`

setuptools-39.0.1 worked for me.

**Comment by adnidor** [comment]
It works now, not sure what changed
